services:
  steambot:
    build: .
    container_name: steambot
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
